"""
Report Generator
Creates human-readable incident reports and audit trails.
"""

from __future__ import annotations

from datetime import datetime

from aerodrift.drift import DriftEvent
from aerodrift.remediation_planner import RemediationPlan


class IncidentReport:
    """A formatted incident report for a drift event."""

    def __init__(self, event: DriftEvent, plan: RemediationPlan | None = None) -> None:
        self.event = event
        self.plan = plan
        self.timestamp = datetime.utcnow()
        self.report_id = f"INC-{self.timestamp.strftime('%Y%m%d-%H%M%S')}"

    def to_markdown(self) -> str:
        """Export report as Markdown for email/wiki."""
        lines = [
            f"# Incident Report {self.report_id}",
            f"**Time:** {self.timestamp.isoformat()}",
            "",
            "## Summary",
            f"- **Severity:** {self.event.severity}",
            f"- **Resource:** {self.event.node_label} ({self.event.node_id})",
            f"- **Resource Type:** {self.event.node_type}",
            "",
            "## Exposure Details",
            "### Exposure Path",
            "```",
            " → ".join(self.event.exposure_path),
            "```",
            "",
            "### Offending Security Groups",
        ]

        for sg_id in self.event.offending_security_groups:
            lines.append(f"- `{sg_id}`")

        if self.plan:
            lines.extend(["", "## Remediation Plan"])
            for i, step in enumerate(self.plan.steps, 1):
                lines.append(f"### Step {i}")
                lines.append(f"**Action:** {step.action.value}")
                lines.append(f"**Target:** {step.target_id}")
                lines.append(f"**Description:** {step.description}")
                lines.append(f"**Risk Level:** {step.risk_level}")
                lines.append("")

        lines.append("---")
        lines.append("*Report generated by AeroDrift*")

        return "\n".join(lines)

    def to_text(self) -> str:
        """Export report as plain text."""
        lines = [
            "=" * 70,
            f"INCIDENT REPORT {self.report_id}",
            "=" * 70,
            "",
            f"Timestamp: {self.timestamp.isoformat()}",
            f"Severity:  {self.event.severity}",
            f"Resource:  {self.event.node_label} ({self.event.node_id})",
            f"Type:      {self.event.node_type}",
            "",
            "EXPOSURE PATH:",
            " → ".join(self.event.exposure_path),
            "",
            "OFFENDING SECURITY GROUPS:",
        ]

        for sg_id in self.event.offending_security_groups:
            lines.append(f"  - {sg_id}")

        if self.plan:
            lines.extend(["", "REMEDIATION PLAN:"])
            for i, step in enumerate(self.plan.steps, 1):
                lines.append(f"  Step {i}: {step.description}")
                lines.append(f"    Action: {step.action.value}")
                lines.append(f"    Risk: {step.risk_level}")

        lines.append("")
        lines.append("=" * 70)

        return "\n".join(lines)


class ReportGenerator:
    """Generates reports for collections of incidents."""

    @staticmethod
    def generate_summary_report(
        events: list[DriftEvent], plans: list[RemediationPlan] | None = None
    ) -> str:
        """Generate a summary report covering all drift events."""
        lines = [
            "=" * 70,
            "DRIFT INCIDENT SUMMARY",
            "=" * 70,
            f"Time: {datetime.utcnow().isoformat()}",
            f"Total Incidents: {len(events)}",
            "",
        ]

        critical = sum(1 for e in events if e.severity == "CRITICAL")
        high = sum(1 for e in events if e.severity == "HIGH")
        medium = sum(1 for e in events if e.severity == "MEDIUM")
        low = sum(1 for e in events if e.severity == "LOW")

        lines.append("BREAKDOWN BY SEVERITY:")
        if critical > 0:
            lines.append(f"  🔴 CRITICAL: {critical}")
        if high > 0:
            lines.append(f"  🟠 HIGH:     {high}")
        if medium > 0:
            lines.append(f"  🟡 MEDIUM:   {medium}")
        if low > 0:
            lines.append(f"  🟢 LOW:      {low}")

        lines.append("")
        lines.append("AFFECTED RESOURCES:")
        for event in events:
            lines.append(f"  - {event.node_label} ({event.node_type}) [{event.severity}]")

        if plans:
            lines.append("")
            lines.append("REMEDIATION SUMMARY:")
            total_steps = sum(len(p.steps) for p in plans)
            lines.append(f"  Total remediation steps: {total_steps}")
            requires_approval = sum(1 for p in plans if p.approval_required)
            lines.append(f"  Plans requiring approval: {requires_approval}")

        lines.append("")
        lines.append("=" * 70)

        return "\n".join(lines)

    @staticmethod
    def generate_audit_trail(
        events: list[DriftEvent], plans: list[RemediationPlan] | None = None
    ) -> str:
        """Generate a timestamped audit trail."""
        lines = [
            "AERODRIFT AUDIT TRAIL",
            f"Generated: {datetime.utcnow().isoformat()}",
            "",
        ]

        for event in events:
            lines.append(f"[DRIFT] {datetime.utcnow().isoformat()}")
            lines.append(f"  Event: {event.node_label} exposed ({event.severity})")
            lines.append(f"  Path: {' → '.join(event.exposure_path)}")
            lines.append("")

        if plans:
            for plan in plans:
                lines.append(f"[PLAN] {datetime.utcnow().isoformat()}")
                lines.append(f"  For: {plan.drift_event.node_label}")
                lines.append(f"  Steps: {len(plan.steps)}")
                lines.append("")

        return "\n".join(lines)